### ISSUE TITLE
Should mailchecker also work on Signup?

### ISSUE THREAD

**Issue by slidenerd** [sahat/hackathon-starter#1041]
In your user.js file you have this line !mailChecker.isValid(req.user.email) under GET /account/verify  which i believe scans to check if user enters blacklisted email domains, dont you think that should also be done on signup?

**Comment by YasharF** [comment]
The barrier to signing up is very low because the primary mission of the project is to get hackathon participants up and running quickly.

The verify email feature was added per https://github.com/sahat/hackathon-starter/issues/674 since many developers use the project outside of the context of hackathons, and it is somewhat of a compromise that provides the feature and sample code on how to do it, but without adding complexity to the sign-up process.  If you like to force the users to use a good email address or to verify if they own the email, feel free to use bits and pieces of the verification as you think applies to your application.
