### ISSUE TITLE
Mongodb error 

### ISSUE THREAD

**Issue by davidnalbandian143** [sahat/hackathon-starter#1049]
driver: true,
  name: 'MongoError',
  index: 0,
  code: 11000,
  keyPattern: { username: 1 },
  keyValue: { username: null },
  errmsg: 'E11000 duplicate key error collection: app.users index: username_1 dup key: { username: null }',
  [Symbol(mongoErrorContextSymbol)]: {}

**Comment by YasharF** [comment]
This seems to be an error because of some new code that you have added to the project which is incorrectly trying to create or update user records.  You can google the errmsg to find out more.  The controllers at https://github.com/sahat/hackathon-starter/tree/master/controllers have some good examples of how to create or modify database records.

**Comment by YasharF** [comment]
Has this issue been resolved?
