### ISSUE TITLE
[Feature Request] Add a rich text editors

### ISSUE THREAD

**Issue by davidnalbandian143** [sahat/hackathon-starter#1053]
I am trying to add rich text editor but the issue is text is not properly display in front end

**Comment by YasharF** [comment]
We need to figure out use cases.

If I understood your request correctly, you would like an example where a user can enter some rich text, which will be displayed on a page after the submission.  Is that correct?

What would be other use cases for a rich text editor that you think may come handy?

**Comment by YasharF** [comment]
Before implementing a solution for this, I would like to see some suggestions on potential solutions.  Please note that one of the current goals is to keep the dependency tree within a reasonable size.

**Comment by Rodriq** [comment]
I'd love to handle this, but then like you mentioned above what are the use cases?
  On what pages will this feature be needed?

**Comment by YasharF** [comment]
@Rodriq I am open to suggestions.  I can think of a few potential use cases:
1. An alternate contact us page (under /api), where the user can format the text being sent to the site admin.
2. A form that the user can enter formatted text, which will be posted back on the page after the submission.
3. A combination, or something else

Note that in both cases, the incoming data needs to be sanitized to avoid potential XSS or other volunerabilites.  It would be also appropriate to have these as a standalone API example (i.e. a view under /api). 

The bigger goal is to have a working example, so developers could quickly modify our example and add their own business logic in order to make the application that they have in mind.

**Comment by dnafication** [comment]
I think a simple blog api (CRUD) can be added to the project which takes in title, subtitle and content. Content will store the rich text (I believe markdown is good enough these days to capture rich text). 

Do you have any suggestion on which editor is suitable for this? I found options below to go with:

1. https://github.com/quilljs/quill/ (this most probably does not return markdown)
2. https://github.com/nhn/tui.editor (this one works with markdown)

**Comment by Athira2199** [comment]
Hi, for text editors we can use something like ckeditor. Its quiet straightforward and has many functionalities. I would like to contribute.
Please refer this link : https://ckeditor.com/

**Comment by abby3010** [comment]
I would like to work on this. Can you assign it to me?

**Comment by abby3010** [comment]
I was thinking about adding the Rich text editor on the contact page by replacing or adding it below the suggestion's textarea.
Alternatively, we can also add it to the landing page below all the headings.

![image](https://user-images.githubusercontent.com/63793110/135960564-ff78962f-6fe8-4c75-bfb5-00852a5d3fe6.png)

Some packages that I found would help are:
[https://www.npmjs.com/package/tinymce]tinymce
[https://www.npmjs.com/package/draft-js]draft-js
[https://www.npmjs.com/package/react-rte]react-rte

If possible can you assign it to me? I'll start working right away!
