### ISSUE TITLE
CSRF error in API for one page application

### ISSUE THREAD

**Issue by fedyfausto** [sahat/hackathon-starter#1055]
Hello i'm going to develop a backend only to provide a set of API (that retus a json repsonde, so without pug templater) for an angular 9 application that was builded and serverd with a static route (the root). Nervertheless, i'm still having the CSRF token missing error on POST request, how could i fix it? (server seems does not release the token in the headers for the client)

**Comment by YasharF** [comment]
It might be a tad bit overkill to strip and modify hackathon-starter to turn it into a JSON only API backend.  Are there features in this project that are gravitating you to use it as only the backend instead of having a custom JSON serving server for your application?

The CSRF token is provided as a meta tag under the Head section of the HTML response

![image](https://user-images.githubusercontent.com/6448697/80236775-7ba17900-8610-11ea-99ff-774634b74ab4.png)

In your response for POST, you would need to provide it as part of the body.  For troubleshooting, In the app.js right about line 95 you can add a `console.log(req.body);` to dump the received submission by the backend, and in there look for the value that is being returned as the _csrf value. Feel free to use an unmodified clone of this project to see how the response is supposed to look like.  The Contact page is probably the easiest for such testing since it doesn't require a registered user.
