### ISSUE TITLE
Twitch integration seems to be broken

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#1078]
500 - Server Error

  oauthError: {
    statusCode: 401,
    data: '{"error":"Unauthorized","status":401,"message":"Client ID and OAuth token do not match"}'
  }

**Comment by dnafication** [comment]
I had a look at this issue. The problem is with the twitch strategy we're using, `passport-twitch-new`. The authentication happens successfully but the request for userProfile is missing a header "Client-ID" which is supposed to be the Twitch Client ID. 

We can either fix the library (right way) or hack around the user profile for now until the library is fixed.  

For more details, following request will success since it has Client-ID but the module does not have that field added currently.

`curl -H "Authorization: Bearer zzzzzzzzzz" -H "Client-ID: zzzzzzzzzz" https://api.twitch.tv/helix/users`

**Comment by dnafication** [comment]
I see that they have updated that code in latest version of the library (`0.0.2`). I will upgrade and send a PR.

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/pull/1085

**Comment by YasharF** [comment]
@dnafication your PR was a duplicate of another PR, however, the change is not fixing the 500 server error.  The error that I see in the current logs is `Error: There was an error while getting user data Error: Request failed with status code 401 `

**Comment by dnafication** [comment]
@YasharF I just tested the latest master. It has your PR #1090 which upgrades the twitch strategy. It seems to be working fine for me. ✅ 

May be try again with new client id and secret.

**Comment by princeyesuraj** [comment]
@YasharF PR #1093 fixes it
