### ISSUE TITLE
Recaptcha Verification

### ISSUE THREAD

**Issue by bkyogesh28** [sahat/hackathon-starter#1103]
As mentioned the recaptcha site key is required and it seems that the key is wrong .I went through the contact site and I can improve the frontend slightly.

**Comment by YasharF** [comment]
https://hackathon-starter.walcony.com/contact is working fine when I navigate to it.

Regarding the potential improvements, please detail them here and get sign-off before sending a PR.  Because of Haktoberfest I have had to mark some incoming PRs as spam, unnecessary, and invalid, and I rather not have your time wasted.  The current focus is the issues marked with "Hacktoberfest" at https://github.com/sahat/hackathon-starter/issues .  If there is a different kind of task that you are looking for (i.e. frontend only), I can potentially come up with something, let me know what you are looking for.  Thanks!
