### ISSUE TITLE
Can we use nodemon by default?

### ISSUE THREAD

**Issue by vimark1** [sahat/hackathon-starter#1251]
Setting up nodemon was one of the first things I did. Shouldn't this be part of the project?

There's a note about nodemon in the README.md but things have moved on since that was written, we don't install things globally so much anymore.

My suggestion is to add `nodemon` as a dev dependency and then add a new `npm run dev` script which uses `nodemon`, `npm start` remains unchanged

Happy to provide a PR if that makes sense

**Comment by umangpatel8123** [comment]
I added nodemon in script and "npm run dev" & created a pull request

**Comment by YasharF** [comment]
Depending on the dev environment, nodemon may or may not work.  Furthermore, I do not recommend it if the dev is using a slower system since it is going to cause high CPU consumption anytime an edit is made, even if the dev still has more changes to make for the current feature and is not ready to preview the changes.  The Readme.md file has instructions for using nodemon and devs can decide to use it if it would fit their personal set up and process.
