### ISSUE TITLE
Suggestion: Use AngularJS on client side

### ISSUE THREAD

**Issue by skyserpent** [sahat/hackathon-starter#185]
It would be so AWESOME to see this boilerplate use AngularJS - like no joke it would be so cool.

**Comment by artforlife** [comment]
While I understand your reasons for not adding Angular and other frameworks, I feel like it would be VERY useful if README was modified to include instructions on how to add those frameworks to this app relatively painlessly. 
I am somewhat new to this and have been struggling for a few days to make it happen (with Angular JS).

**Comment by sahat** [comment]
@artforlife I'll see what I can do. The reason why you are struggling is exactly the reason why it would be hard to drop in React or Angular to this project as it requires swapping out a lot of parts, authentication & session management piece being the most difficult one.

**Comment by artforlife** [comment]
@sahat Much appreciated mate! This is a great project otherwise. I have already learned a lot just by digging through the code and seeing how it works!

P.S. My biggest problem is actually figuring out the routing because the one-page Angular app I am trying to port has its own routes, whereas Node and Express are responsible for login and database queries. If I could make a suggestion, perhaps you could introduce a route, say, "main" around which one could build a single-page app using Angular or other frameworks, that may be helpful. This way it does not tear up the entire project, but makes such addition more feasible.

**Comment by badreal** [comment]
@artforlife if you use angular, your nodejs app should be mainly used as an api, so you don't need route for the views, you only need api route rendering json data. as @sahat pointed out, user management and authentication are the main issue, for the rest, you can really split your app in two parts, client and server, and make your angular services call the rest api provided by nodejs. but the main issue is handling authentication which will be pretty hard to do with the current project structure.
