### ISSUE TITLE
MongoDB Connection Error. Please make sure MongoDB is running

### ISSUE THREAD

**Issue by stephnr** [sahat/hackathon-starter#20]
Im getting this as an initial error when trying to run the code for the first time. This is my first time working with node.js applications. 

Also, it would be ultra-awesome if you (OP) would consider doing screencasts of tutorials on effectively using this tool. I would love to advocate your project at future hackathons.

**Comment by slidenerd** [comment]
how did you fix it @draschke  if you mind telling

**Comment by gauravparashar12** [comment]
I also have the same issue i simple run the command (mongod) to run mongo db  in another terminal

**Comment by sikanth** [comment]
Hi @draschke , How do you fix that problem

**Comment by Nikitas-io** [comment]
> Hi @draschke , How do you fix that problem

I know I'm way lay to the party, but I'm going to reply to this message in case someone stumbles upon this problem in the future. In my case, I was trying to connect to MongoDB Atlas (MongoDB Cloud) but I could not do it because MongoDB was running in the background of Windows, blocking my connection to Atlas. To solve this problem I had to open up the PowerShell prompt as an administrator and type in the `net stop MongoDB` command to terminate the MongoDB process.

**Comment by hijazi** [comment]
Hi @sikanth @slidenerd, for me it didn't work on Ubuntu and the log said I need to create the data folder (the error `"error":"NonExistentPath: Data directory /data/db not found. Create the missing directory or specify another path using (1) the --dbpath command line option, or (2) by adding the 'storage.dbPath' option in the configuration file."}}`) so I created a folder in my home directory data/db and specified it when run the mongod and everything worked fine.
