### ISSUE TITLE
Redirects to logo image file or public CSS file on login

### ISSUE THREAD

**Issue by DaddyWarbucks** [sahat/hackathon-starter#214]
I am having a very weird problem that I cannot pinpoint. The user is being redirected to public files after login. 

Scenario: The user logs in (via email or Oauth), the application does successfully recognize and authorize this login, then the user is redirected to "http://localhost:3000/img/logo.png" or "http://localhost:3000/public/css/style.css". The user then hits the "back" button, which redirects them to the proper page (not back to /login)

Desired Scenario: Scenario: The user logs in (via email or Oauth), then is redirected to the route I set (ie /account)

Possible problems: I am not super savvy on the asset pipeline and and/or LESS, so I have extruded that out and am using a simple style.css. I doubt that is a contributor to the problem, but since it redirects to either the logo or css file, I thought I might include this info.

Thanks for any help!!

**Comment by DaddyWarbucks** [comment]
I have also that " #_=_ " is appended to the end of the URL

**Comment by sahat** [comment]
> I have also noticed that " #= " is appended to the end of the URL

Are you seeing it when you login with Facebook? It's a common issue that has been around since forever.

Regarding your redirect, I am almost positive it's due to this code:

```js
  // Remember original destination before login.
  var path = req.path.split('/')[1];
  if (/auth|login|logout|signup|fonts|favicon/i.test(path)) {
    return next();
  }
```

In order to redirect you to the right place after login, it keeps track of the previous request, which unfortunately can be a request not just to a valid page but also to images, fonts, icons, favicons, styles. The regex above basically excludes the following paths. I may reverse the logic in the next version, where it excludes everything by default and only remembers original destination on pre-determined routes.

**Comment by sahat** [comment]
So add img and css to the above regex and it should fix the issue:

```js
  if (/auth|login|logout|signup|fonts|favicon|img|css/i.test(path)) {
    return next();
  }
```

**Comment by DaddyWarbucks** [comment]
Thanks so much!
