### ISSUE TITLE
Remove Node-Sass Dependency 

### ISSUE THREAD

**Issue by geggleto** [sahat/hackathon-starter#228]
Hi,

Is it possible to remove the node-sass dependency ? I have tried the last 3 stable branches and none of them build... The 2.0.0beta doesn't work either. Anyone new discovering this package will not be able to run it without first removing all of the node-sass components.

Related to #222 

Thanks

**Comment by sahat** [comment]
Hey @geggleto are you not able to install `node-sass`? That library uses native C++ extensions so if you are running on a machine without Xcode (mac), Visual Studio (Windows), `build-essentials` (Ubuntu), chances are you will not be able to install that package.

I only recently switched from LESS to Sass and would prefer to avoid rolling back to LESS. Agreed, it was a little easier with LESS because it doesn't have any C++ dependencies.

Mongoose and mongodb-native-driver, I believe also require a c++ compiler installed on your computer, so `node-sass` dependency is not just a one-off case.

The 2.0.0 Beta will not work with hackathon-starter yet since [connect-assets](https://github.com/adunkman/connect-assets) does not currently support it.

**Comment by geggleto** [comment]
Hi @sahat  I was building on Centos 6.6 with the Development Tools group package. node-sass does not compile on my dev server or vagrant instance (both same versions as mentioned above) which has been incredibility annoying  

While I understand that it is apart of the tool chain for this particular package, I do believe on a fundamental level that it should be easily disabled or at least made a non-core component.  Perhaps some additional work in the setup.js file could accomplish this task. 

I will continue however to try and find out how I can get the C++ dependencies to install in my particular distro (although I haven't found very many resources on it).

I would appreciate any guidance in how I can remove the node-sass from this package in the mean-time.

Thanks for the great package though!

**Comment by geggleto** [comment]
Updating my gcc version fixed the issue with node-sass

**Comment by sahat** [comment]
Ah, it seems you had the same issue as me at work on one of the Docker containers. The GCC version was outdated which prevented me to install node-sass package. I ended up switching to LESS since I had no control of GCC version on that server.

If you do however want to use LESS without all this Sass dependency nonsense you can grab all the assets from here:

https://github.com/sahat/hackathon-starter/tree/84387a6ca6582ae5c4d7078dfd1ca0667680e4c3/public/css

**Comment by geggleto** [comment]
@sahat  You sir rock. ty

**Comment by geggleto** [comment]
For those who find this... 

http://superuser.com/questions/381160/how-to-install-gcc-4-7-x-4-8-x-on-centos

For CentOS gcc updates
