### ISSUE TITLE
Contact err: "Invalid login"

### ISSUE THREAD

**Issue by Patrax** [sahat/hackathon-starter#229]
When submitting the contact form you get the error "Invalid login".
Any hints as to what could be causing this during production?

**Comment by sahat** [comment]
In **controllers/contact.js** is where you pass your SMTP service username and password:

```js
var transporter = nodemailer.createTransport({
  service: 'SendGrid',
  auth: {
    user: secrets.sendgrid.user,
    pass: secrets.sendgrid.password
  }
});
```

It probably refers to that login error. The default username and password I provided in this project were probably banned since this is a sensitive information that you shouldn't share with anyone. However, I did it for convenience reasons.
