### ISSUE TITLE
Cannot connect on my account when all third party have been unlinked

### ISSUE THREAD

**Issue by mastilver** [sahat/hackathon-starter#241]
Steps to reproduce:

- login with Github
- go to the account screen
- unlink Github
- logout
- try to login with Github

You should come up with this message: 'There is already an account using this email address. Sign in to that account and link it with GitHub manually from Account Settings.'

Btw really good project, I used it and will continue to use it in the future

**Comment by mastilver** [comment]
I guess if you use the forget password link you can access your account although it wouldn't work with Twitter because the email address is a fake one

**Comment by sahat** [comment]
Hey @mastilver, while I see what you are saying and I could reproduce it, fixing it is not so trivial. On one hand I could merge these two accounts if the email is the same, on the other hand it should prompt the user if it detects that you're unlinking the last social account, since you will not be able to login again without setting the password first. If I merge two accounts based on the same email, someone will come here and say to implement a feature that supports merging accounts when you have multiple emails (e.g., Google, Facebook). If I choose to prompt the user when unlinking the last social account it would require hard-coding the names to keep track of all linked social accounts.

So I would not call this a bug, but rather an unimplemented feature. Because at that point it becomes more about your particular application logic, rather than a generic boilerplate use case.
