### ISSUE TITLE
browser history (cached website files) should be removed for each application.js update!

### ISSUE THREAD

**Issue by ehsankhfr** [sahat/hackathon-starter#260]
Hi,

I have recently started to use the hackathon. for any updates inside the /public/js/application.js and all manipulated referenced .js files in this folder, I have to clear the history of the browser.
After clearing the history of the browser, I can see the changes inside the .js codes :)

How can I solve it?

**Comment by sahat** [comment]
You can disable the cache while Chrome's Dev Tools is open, which at least for me, it is open 99% of the time during development.

![screenshot 2015-04-13 12 48 18](https://cloud.githubusercontent.com/assets/544954/7124099/6d51fbf6-e1db-11e4-9751-0a063d7b5302.png)

Alternatively, press **Command + Shift + R** to do a "hard page reload" in Google Chrome. You will have to check for the exact shortcut on Windows and Linux, or if you are using the Firefox.

You don't have to worry about this issue in production because application.js will have a cache buster string appended like so:

```html
<script src="/assets/application-e65cdcaf707c342e1a7bc8c876209ba0.js"></script>
```
