### ISSUE TITLE
Bootstrap glyphicons

### ISSUE THREAD

**Issue by chrisvdb** [sahat/hackathon-starter#272]
Hi there,

I was wondering how to enable Bootstrap glyphicons in Hackathon-starter.

I tried:
- downloading the glyphicon fonts into public/fonts
- downloading the glyphicon.less file into public/css/vendor/bootstrap

But this didn't work. Any idea?

Also, I would be grateful if somebody could explain the link between the "public" directory and "/asset" URL path. My current understanding is:

- public/css: files listed in main.less become accessible under a single file /assets/main.css
- public/js: files listed in application.js become accessible under a single file /assets/application.js
- public/fonts: all files are individually accessible under /assets/fonts/<filename>

Is that correct?

Should I put images under public/images? Will they become available under /images/<filename> or /assets/images/<filename>?

Thanks,
Chris.

**Comment by sahat** [comment]
I deleted one line in `bootstrap.less` which is why it wasn't working for you even after you added *glyphicons.less* file.
```
@import "glyphicons.less";
```

Add that back and it will work for you.

This project does not use `/assets` path for anything. Everything inside **public** is directly accessible from the browser without any URL prefixes. If you create a new folder images inside **public**, in your HTML it will simply be `/images/some_image.jpg`.

> public/css: files listed in main.less become accessible under a single file /assets/main.css
Yes, handled by connect-assets module.

> public/js: files listed in application.js become accessible under a single file /assets/application.js
In development mode, each file listed in application.js will show up as inidividual file if you inspect HTML source. In production mode, everything will be minified and concatenated in application.js. Again, handled by connect-assets.
