### ISSUE TITLE
Why not use Satellizer in your starter ?

### ISSUE THREAD

**Issue by jbeurel** [sahat/hackathon-starter#281]
Hi @sahat.

First of all, Satellizer is an impressive project. Thanks for it.

Satellizer is an alternative to Passportjs and you explain its implementation with Express.

Why not use it with an Angularjs frontend ?

**Comment by sahat** [comment]
Hey @jbeurel, thank you. But let me clarify a few things.

Satellizer is really designed for single page applications using AngularJS. It does not fit into Hackathon Starter because this project doesn't use AngularJS to begin with. This boilerplate project centers around simplicity and ease of use, adding a JavaScript framework like Angular or React would result in an entirely different boilerplate project and it shouldn't called hackathon-starter anymore.

Not to mention there is a constant battle on the front-end: AngularJS 1.x vs 2.0 (completely redesigned), Angular vs Ember vs React vs shiny new framework every 2 weeks. You pick one framework for this project and you immediately exclude everyone else who doesn't like or cannot use that JavaScript framework. For that reason I have kept it "vanilla node.js" as much as possible since the beginning, despite moving on to different frameworks since then - 1) **Ember.js**,  2) **AngularJS**, and now 3) **React + Flux + ES6** for my own personal projects.

**Comment by jbeurel** [comment]
Thanks for your very clear answer.
