### ISSUE TITLE
Move Routes into another file

### ISSUE THREAD

**Issue by JahlomP** [sahat/hackathon-starter#296]
Wouldn't it be better to move routes into another file and export it from there to be used in app.js?

**Comment by sahat** [comment]
I don't see what is the advantage of moving routes into a separate file? Seems like a preference issue. I have seen people going with extremes of having only 1-5 lines of code in `app.js` and everything else is split into routes, middleware, starting the server, some crazy app wrappers, etc. 

I find it easier when you have all the routes in one place inside `app.js`, and since simplicity is the main focus of this project, that's why it is the way it is.

**Comment by JahlomP** [comment]
OK sure.

**Comment by ruandao** [comment]
will this make sub app more reuseable?  
just like django, it's sub app was pluggable
