### ISSUE TITLE
application.js not getting minified.

### ISSUE THREAD

**Issue by thngdude** [sahat/hackathon-starter#314]
I'm a bit confused about setting the project to development vs production. To be honest, I am not a black belt node-er either. 

I'm deploying to a Digital Ocean droplet running dokku, and am unsure how the env vars are supposed to be setup for this project.

I've tried not setting anything - simply deploying the project and it is running in 'development' mode. main.css seems to be concatenated but not minified and application.js does not concatenate nor minify my js files although they're all referenced in application.js.

I've also tried setting my package.json as

"scripts" : {
    "start" : "NODE_ENV='production' node app.js"
}

... which runs the app in 'production' mode, but the main.css and application.js files are appearing as "/assets/main-d0d308915afe66b143bed9e94cd5d349.css" and "/assets/application-62b40e71b4f023fabc1dcb475408dcb7.js" ... what are the dash and strings that are attached?

My question is "is there a proper way to be deploying in production?".

**Comment by sahat** [comment]
I haven't deployed a node app to anything other than PaaS like Heroku, OpenShift, Azure where they take care of env variables for you. So I can't tell you what's the best practice when it comes to that. But if your approach works then use that. And perhaps add another script to package.json called `start-dev` that runs it without production environment.

The hexanumeric part is called a cache buster and is fairly common concept in web dev. Let's say you make a single change to main.css, upload your new changes to Digital Ocean, visit your site but you will still see your old main.css because it was cached by Express. So you do `Command + R` or `Ctrl + R` to refresh the page, or clear the browser's cache manually to see new CSS changes. Cache buster always gurantees that when you update your JS or CSS files, users will see your new changes without having them clear the cache or perform hard page reload.

**Comment by thngdude** [comment]
@sahat Hey, this is a great project - so, first of all, thanks for creating/maintaining it! 

I got it working. The problem appears to be that I had a .less file (imported in main.less) in the public/css folder. I'm not sure why (and maybe you can offer an explanation), but when I shifted it into public/css/[new folder] it worked.

Thanks for explaining cache-busting. I wasn't previously familiar with the concept, but it's awesome! I'll close the issue now.

**Comment by rickitan** [comment]
Hi @sahat 

Amazing project. I've been using it a lot!! 

Sahat I'm curious about how does the app know that it's on production ? I'm setting the process.env.production to true when I deploy on my server. The problem that I'm having is that the cache busting doesn't seem to be working, I updated a public JS file but when I check the content of the minimized one the new code is not in it. 

How does the app decide when to minimize and when to serve separate files ? Do we use a node module that does this ? 

Thank you so much, 

-Ricardo
