### ISSUE TITLE
Auto generate templates based on the template engine you choose

### ISSUE THREAD

**Issue by macmichael01** [sahat/hackathon-starter#322]
This might be complete insanity. Updating the setup script to allow the developer to choose between the template engine of their choice and then auto generate these templates.

**Comment by sahat** [comment]
@macmichael01 There was a similar request for the Handlebars templating recently. Long story short it would be a maintenance nightmare to maintain two template engines. It is certainly doable, but crazy amount of work for me. If you have good recommendations for tooling I may consider doing it, not just for Handlebars but for Swig as well, and maybe even extend it to Sass and LESS stylesheets.

I had a horrible experience with managing OAuth passport strategies add/remove logic via setup.js. It was so brittle because it relied on very precise line numbers, and if it was off by a little it would break the entire thing.

**Comment by sahat** [comment]
I will close this, but I will keep the idea in mind, perhaps for my next project that will be hundreds of times more customizable and much bigger in scope than hackathon-starter.
