### ISSUE TITLE
Security question, consider adding secrets.js to .gitignore

### ISSUE THREAD

**Issue by jimthedev** [sahat/hackathon-starter#350]
Hi there, 

Great project and thanks for it.

Just a quick security gripe. Having secrets.js not listed in .gitignore encourages people to accidentally check their passwords / secrets into source control.

A possible better solution is to offer secrets.sample.js by default, then ask users to rename secrets.sample.js to secrets.js. This way you could have secrets.sample.js checked into scm but secrets.js would be ignored by default. 

Just a thought from a first time user of this project so please let me know if I am mistake or if there is a better way to handle this w/o crippling the project.

Cheers!

**Comment by egladman** [comment]
+1

**Comment by sahat** [comment]
:+1: Great suggestion. I have added some comments at the beginning of the file regarding security concerns, but renaming file to example or sample may reinforce that idea.

The right approach here is probably what [FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp) (fork of hackathon-starter) is doing using [dotenv](https://github.com/bkeepers/dotenv) package. 

There was a pull request to add `dotenv` to this project back in 2014 but I closed it because I wanted to keep hackathon-starter as simple as possible, however,I will give it another consideration. At the very least I am going to rename the file to `secrets.sample.js`.

**Comment by sahat** [comment]
Fixed in https://github.com/sahat/hackathon-starter/commit/4a38809779713eccd96e0e8e2ea4e318482f1ad4.

**Comment by sahat** [comment]
I have also added `.env` to .gitignore, so that when the file is renamed from `.env.example` to `.env` it will not be added to Git accidentally.

After renaming the file, inside *app.js*:

```js
dotenv.load({ path: '.env.example' });
```

Simply becomes:
```js
dotenv.load();
```
