### ISSUE TITLE
JSON Web Tokens

### ISSUE THREAD

**Issue by niallobrien** [sahat/hackathon-starter#353]
Do you think it would be worthwhile to add support for JWTs? Especially for those that are building SPA or hybrid web apps. Thanks.

**Comment by sahat** [comment]
No not for this project. Hackathon Starter does not come with a client-side framework to begin with. Those who are planning to modify this boilerplate to be used with Ember/React/Angular/etc. will find a proper authentication library for that framework which may or may not use JWT. In any case, since hackathon starter is designed to be a traditional web app out of the box, not a single-page app, it doesn't make sense to add JWT support.

**Comment by niallobrien** [comment]
Fair point and I completely understand it may not be suitable for this project. Just for the record, I like to develop regular server-side apps, render the JWT in the layout and if/when you need to do an ajax request (even with jQuery) to a secure API endpoint, JWTs are awesome.

**Comment by sahat** [comment]
Sounds a lot like CSRF token used in this project. It was added quite a while ago, but if I remember it was for client-side testing and AJAX POST requests:

```jade
doctype html
html
  head
    meta(charset='utf-8')
    meta(http-equiv='X-UA-Compatible', content='IE=edge')
    meta(name='viewport', content='width=device-width, initial-scale=1.0')
    meta(name='csrf-token', content=_csrf)
```
