### ISSUE TITLE
Generator name is confusing

### ISSUE THREAD

**Issue by simondiep** [sahat/hackathon-starter#361]
I'm new to the project and was reading through the readme.  I was very confused when I read the section titled Generator.  I played around with it and found out that the generator file 'setup.js' is more for app customization.  Could the description be updated or a different term be used?

Thanks!

**Comment by sahat** [comment]
I will likely remove it soon. At one point it used to add code, like new authentication providers, but due to complexity and many bugs I had to remove it. IMHO it does not provide much value anymore and I agree generator is a bit confusing.

Now for the good news, I am working on the original concept of "generator" in a separate project. It's like a hackathon starter where you can customize every part of your stack - sass vs less vs css, jade vs handlebars, express vs hapi, 5+ authentication providers where you can pick just the ones you need, react or angular optionally, ES6 vs ES5, mongodb vs mysql vs postgresql, mocha vs jasmine...etc.

<img width="897" alt="screenshot 2015-12-17 08 58 36" src="https://cloud.githubusercontent.com/assets/544954/12693433/bf443794-c6d7-11e5-9642-a7c1b3f451cc.png">

**Comment by talha131** [comment]
> Now for the good news, I am working on the original concept of "generator" in a separate project.

Any update on this? 

Thanks for your great work. I found it really helpful.
