### ISSUE TITLE
Is it possible to easily add SQL support?

### ISSUE THREAD

**Issue by dortzur** [sahat/hackathon-starter#362]
I would like to support sequelize orm, I might create a pull request. Was wondering what are your thoughts on this?

**Comment by niallobrien** [comment]
@dortzur I'd love to see this, especially if you integrate all of the user auth functionality etc.

**Comment by sahat** [comment]
Switching from Mongoose to Sequelize will require changing a big part of this project, including all of auth, login, registration, forgot password. 

Trying to optionally support it via `generator.js` will be difficult and not maintainable in the long run, on the other hand allowing users to switch between MongoDB and your choice of SQL database in the code will come at a big cost to simplicity of this project. That will require adding higher-level wrappers that could abstract away database-specific logic. IMHO not worth it.

I am going to keep MongoDB in this project because I still believe it to be valuable for beginners and the audience that hackathon starter is targeting, despite some criticism about MongoDB on Hacker News.

If you haven't seen seen my post on Twitter, I am working on a new project, much bigger in scope than hackathon starter, that allows you to customize every part of your stack. It's like every possible variation of hackathon starter, all dynamically generated on the fly.

![screenshot 2016-01-31 14 58 30](https://cloud.githubusercontent.com/assets/544954/12704528/2364c3c0-c82b-11e5-8f7d-95e659aa7360.png)
![screenshot 2016-01-31 14 58 06](https://cloud.githubusercontent.com/assets/544954/12704529/23674cd0-c82b-11e5-80b3-4e7bf1927296.png)

**Comment by dortzur** [comment]
Really Cool!
I could really use something like that.

**Comment by sahat** [comment]
I will close this, if that answers your question about Sequelize. @niallobrien you should get in touch with @dortzur and perhaps work together on migrating Mongoose to Sequelize.

**Comment by dortzur** [comment]
When will the new tool available do you think?
Yeah I'll fork it and see how it goes. 
Thanks!

**Comment by sahat** [comment]
@dortzur It is still in early stages. There is a lot of work that still needs to be done. For instance, I can't simply create new a UI like I did with hackathon starter, because I can't make assumptions about anything - will user choose Handlebars or Jade or Nunjucks template engine? That will require completely different markup for each one. Furthermore, can't make assumptions if they will choose Bootstrap, Foundation or Bourbon CSS frameworks, or none at all. Will they choose React or Angular? That will completely change the way an app is rendered, using new templates, new routes, etc. As you can see there are a lot of states, and each state has to be accounted for.

**Comment by jigs1212** [comment]
> Switching from Mongoose to Sequelize will require changing a big part of this project, including all of auth, login, registration, forgot password.
> 
> Trying to optionally support it via `generator.js` will be difficult and not maintainable in the long run, on the other hand allowing users to switch between MongoDB and your choice of SQL database in the code will come at a big cost to simplicity of this project. That will require adding higher-level wrappers that could abstract away database-specific logic. IMHO not worth it.
> 
> I am going to keep MongoDB in this project because I still believe it to be valuable for beginners and the audience that hackathon starter is targeting, despite some criticism about MongoDB on Hacker News.
> 
> If you haven't seen seen my post on Twitter, I am working on a new project, much bigger in scope than hackathon starter, that allows you to customize every part of your stack. It's like every possible variation of hackathon starter, all dynamically generated on the fly.
> 
> ![screenshot 2016-01-31 14 58 30](https://cloud.githubusercontent.com/assets/544954/12704528/2364c3c0-c82b-11e5-8f7d-95e659aa7360.png)
> ![screenshot 2016-01-31 14 58 06](https://cloud.githubusercontent.com/assets/544954/12704529/23674cd0-c82b-11e5-80b3-4e7bf1927296.png)

Any update on the project ? I also want to use MySQL.

**Comment by YasharF** [comment]
That project was outside of the scope of Hackathon-Starter.  I believed it ended up turning into https://github.com/sahat/megaboilerplate however, MegaBoilerPlate is no longer being actively maintained.
