### ISSUE TITLE
Pinterest OAuth and API Examples

### ISSUE THREAD

**Issue by theGrue** [sahat/hackathon-starter#381]
As per the contribution guidelines, I'm opening an issue before a pull request. :)

I needed to check out some Pinterest OAuth and API functions, so I started with this excellent base and used [passport-pinterest](https://github.com/analog-nico/passport-pinterest) to include a "Sign in with Pinterest" feature. I also added a section to the API Examples page, though there doesn't seem to be a great Node library for Pinterest, so I'm just using Request to do the work there.

Let me know if you'd be interested in a PR! We'd probably need to work together to create a "Hackathon Starter" Pinterest app to use by default.

**Comment by sahat** [comment]
HI @theGrue, Pinterest API addition would be nice, but use `passport.authorize` instead of `passport.authenticate`, similar to Foursquare API example. In other words, don't add "Sign in with Pinterest" functionality.

For the API example itself, try to limit to at most 2 routes - GET and POST. For something like Pinterest, just one GET route would probably be sufficient to fetch user's pins, popular pins, etc.

**Comment by sahat** [comment]
@theGrue What's the status of this PR?

**Comment by theGrue** [comment]
Hey, I'll have to do a little cleanup (and remove the "Sign in with Pinterest" that I'm currently using), but I'll submit something soon.

**Comment by sahat** [comment]
Ok, thanks for the update!
