### ISSUE TITLE
Stripe Create Charge

### ISSUE THREAD

**Issue by tbonz** [sahat/hackathon-starter#402]
It seems as though the instantiation of the stripe var should be moved into the postStripe method.  That is where the var stripe is used to create the charge.  Let me know your thoughts.

Here's a commit showing the changes in my own fork.

https://github.com/tbonz/hackathon-starter/commit/b6f51a8439285f4edf3d7c781f40fe29e586354f

**Comment by sahat** [comment]
@tbonz It won't really make any difference, unless you are hitting `postStripe` directly via XHR request. Ideally, I would leave initialization at the top, as before, but this change was necessary to speed up app start-up time.

Since I am already initializing all other API examples inside a GET route, it does not make sense to have an exception case for Stripe.

**Comment by tbonz** [comment]
Thanks for the explanation, I understand now why you have it setup this way.
