### ISSUE TITLE
Move source styles

### ISSUE THREAD

**Issue by niallobrien** [sahat/hackathon-starter#405]
Just wondering what you all think about moving the source styles from `/public` to somewhere like `/assets/styles`?
This would ensure that source styles aren't publicly accessible. I'm happy to submit a PR for this if the change is acceptable.

**Comment by sahat** [comment]
I think it's fine the way it is. It won't do any harm if someone stumbles upon Sass files by going to http://yoursite.com/css/main.scss, assuming one knows that is the actual directory structure on a server. 

It would make more sense to have `assets` folder if there was a gulp or webpack compiling, minifying, optimizing both CSS and JS files, and then copying them to `public` folder.

I am also trying to avoid adding more top-level directories to the project. Not to bash on other's work, but this is what happens when you add, add, and keeping adding more stuff until it becomes hard to understand what is what anymore: https://github.com/meanjs/mean.
