### ISSUE TITLE
Cookie Parser Middleware

### ISSUE THREAD

**Issue by tbonz** [sahat/hackathon-starter#406]
@sahat can you explain the need for the cookie parser middleware?  It's my understanding that express session no longer uses this as of 1.5.0 (https://github.com/expressjs/session#cookie-options), and is not needed to implement passport or other session stores.  I could not see where the cookie parser middleware was being used in the application.  Possibly you would able to prune this from the current dependencies.

**Comment by sahat** [comment]
Ah you may be right. I have been copy and pasting these middlewares from other sites when I built hackathon-starter. I will remove it since it is not being used for anything in particular.

**Comment by tbonz** [comment]
.. one other item I was looking at while refactoring was the method override middleware.  It's possible this could be pruned too.  Let me know what you think.  Since express 4 the app object allows you to route via app.get, app.post, app.put, app.delete.. and so I'm not clear how the method override middleware would be needed.

**Comment by sahat** [comment]
Ah good question. I was actually working on that a few days ago on my upcoming boilerplate project.
https://github.com/sahat/boilerplate/blob/master/generators/authentication/modules/common/views/profile.jade#L16

I am not using it in this project, but the idea is you can have REST routes while still using `<form>` which only supports GET and POST. That's why in hackathon-starter I am using non-rest routes like POST /account/password and /account/profile to update data (where PUT is more appropriate). The same goes for deleting an account.

So I could either remove method-override, or update routes to use it like you see in the link above.

**Comment by tbonz** [comment]
The boilerplate project looks great! Can't wait to see when it's finished.  

I enjoy the simplicity of hackathon starter, and so my vote would be to remove the method override middleware making it less complicated to understand when first starting a project.  However, I also see the benefits of updating the routes and creating actual REST routes.  

Tough decision, so I'll leave it up to you to decide if updating the routes makes more sense for this project or not.
