### ISSUE TITLE
Mandrill no longer allows programmatic emails

### ISSUE THREAD

**Issue by code-for-coffee** [sahat/hackathon-starter#410]
Might want to remove the reference to Mandrill. They're merging Mandrill into MailChimp and are shutting it off as it currently exists.

http://blog.mailchimp.com/important-changes-to-mandrill/

**Comment by KevinBusse** [comment]
SparkPost has offered to take on any departing Mandrill users and to honor Mandrill’s pricing for those users.

So, moving to SparkPost might be an option
https://github.com/SparkPost/nodemailer-sparkpost-transport

**Comment by sahat** [comment]
Well, this sucks, all my accounts have been disabled with Sendgrid (3 accounts), Mailgun (2 accounts) and Mandrill. Each one of them has also made it increasingly more difficult to create a new account with their domain verification process. Sparkpost, I believe only allows sending emails from a valid verified domain name, i.e. *localhost:3000* is not a valid domain.

I am going to close this as **wontfix** because you should be using your own account anyway, even if I create a new fake account with Mailgun or Sparkpost, it will be banned again because anyone is free to abuse these API keys as soon as they are publicly available on GitHub.

**Comment by sahat** [comment]
I am going to remove all the references to Mandrill at least.

**Comment by code-for-coffee** [comment]
@sahat - developers should just use the `dotenv` library/module/etc for whatever project they're using to hide those keys. Those baddies.
