### ISSUE TITLE
jade - ng-app preventing POST only GET

### ISSUE THREAD

**Issue by carlos09** [sahat/hackathon-starter#418]
So I am a little new to this but came across something odd. While i was setting up a controller, I noticed that when I add ng-app to the html or body tag in the jade file, it prevents being able to make POST requests such as logging in or signing up a user.  Not sure if there is something I am overlooking here. Is there a different way I should go about this?

**Comment by sahat** [comment]
This is probably an Angular thing. http://stackoverflow.com/questions/31620015/why-does-not-form-send-post-request-on-submit-in-my-angularjs-app-after-creating

With React, I explicitly do `event.preventDefault()` to prevent form submit, but I think Angular does it automatically.

Now, it is by design, since you don't want to reload the page on form submit in a single page application, but instead send an AJAX request via $http.post() in Angular.
