### ISSUE TITLE
Error thrown on $ node app.js

### ISSUE THREAD

**Issue by iamchriswick** [sahat/hackathon-starter#461]
After following the instructions I can't seem to get this working.

On `$ node app.js` I only get the following error:

```
» node app.js
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
```

**Comment by ChrisVent** [comment]
The port (3000) is already in use. Try to run the app in a different port.
Example, In app.js file replace 3000 with 8080:
```javascript
app.listen(8080);
```

**Comment by sahat** [comment]
You are running another process on port 3000. Sometimes even when you forcibly close a Terminal, an app server can still be running in the background until you restart your computer.

**Comment by KevinBusse** [comment]
You can also see what else is running and which pid it uses, so you can kill the process instead of restarting your computer.

`$ sudo netstat -nlp | grep -e ":3000\b"`

You should get sth similar to the following line where 23788 is the PID:

`tcp6       0      0 :::3000                   :::*                    LISTEN      23788/node`

**Comment by iamchriswick** [comment]
Thanks, fixed it with `$ kill -9 3000`
