### ISSUE TITLE
Detecting when application is in deployed enviornment

### ISSUE THREAD

**Issue by HellerCommaA** [sahat/hackathon-starter#569]
@sahat 

I wanted to know your thoughts on a PR for this. Basically, when apps are deployed (process.env.NODE_ENV == 'production'), the mongo connect string still references a locally hosted mongo instance. Obviously this isn't a good practice and I'm not sure it's something we should be pushing, moving forward. (Secondly, it does this with sessions as well). It should reference process.env.MONGOLAB_URI

I've got a solution that I use in my production servers if you'd like a PR.

Additionally, .env files shouldn't be included in git files at all. There is a GREAT package https://github.com/xavdid/heroku-config that makes pushing these amazingly easy to Heroku. In my case, I determine ``` if (process.env.NODE_ENV != 'production') { dotenv.load({ path: '.env' }); } ``` and allow heroku to use actual enviornment variables for the production server (synced via the above package).  If you'd like a second PR for this, lemme know!

Adam

**Comment by sahat** [comment]
@HellerCommaA If you rename `.env.example` to `.env` it should be automatically "gitignored" and thus never reach Heroku.

**Comment by HellerCommaA** [comment]
Yeah, I know it's in the .gitignore. Maybe I'm not explaining this correctly. Haha.  It's been a long day at work.  I'll shoot you 2 PRs tonight to show you what I mean, although one will be fairly Heroku specific, which may not work.

**Comment by HellerCommaA** [comment]
@sahat sorry that took a minute. Got distracted.

https://github.com/sahat/hackathon-starter/pull/571 is the database specific PR.

**Comment by sahat** [comment]
@HellerCommaA After looking at your PR, I still don't think it is necessary. In production, if you have set `MONGOLAB_URI` or `MONGODB_URI` environment variables, the app would would use them. 

It shouldn't even work otherwise because if `.env` is not present (assuming you didn't push straight to Heroku with `.env.example` file), those env vars should be undefined in production.

On a related note, an issue with that `if` statement, it uses `MONGOLAB_URI` only in production, but what if a user wants to use `MONGODB_URI` variable in production (presumably because they use something other than mLab)? Or what if I want to connect to a `MONGOLAB_URI` from a development environment?

**Comment by sahat** [comment]
Closing this issue since I haven't heard back in 2 weeks. Feel free to re-open again.
