### ISSUE TITLE
Using CDNs for libraries

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#574]
During the course of a hackathon it makes a lot of sense to have files locally so we don't miss dev time due to networking issues.  But when it comes to deploying, lets say to somewhere like the free tier of Heroku it would be helpful to keep static files off of the host as much as possible, so when a bunch of requests come in the server, it doesn't have to worry about the static stuff.

I am thinking what might be awesome is to have some type of prod flag, etc that when is set instead of the local copy of Bootstrap, JQuery, Font Awesome, one of the popular CDNs are used.  Aka, the file addresses at the following addresses:
https://www.bootstrapcdn.com
https://code.jquery.com
https://cdnjs.com/libraries/font-awesome

However, cheaper than that would be for the developer to just change their code to point to the CDN copies instead of their own local copies.  For the JS files, it seem to be pretty easy since it is just swapping two lines at https://github.com/sahat/hackathon-starter/blob/master/views/layout.pug#L22 , but for the other stuff like the CSS files, I think I saw that they are folded into other css files like main.css.  Is that correct?  Is there a reason not to use the libraries from the CDNs, besides the need for some potential refactoring?  Would you be able to do the refactoring?

**Comment by sahat** [comment]
Hi @YasharF, I agree static files should move to CDN or S3 in production. But at the same time I am against the idea of adding flags to the templates in this project. I would either consider switching all libraries to CDN urls or keeping it local (as-is). And based on my past experience and as you have mentioned, networking issues are not uncommon.

Personally, I think this exercise is best left to the user. If someone wants to use CDN, it's a matter of updating 2 lines of code.

For CSS, yes, since Hackathon Starter is using Sass, all styles, including vendor files, are concatenated into a single `*.css`file.

**Comment by deadcoder0904** [comment]
Taking this up

**Comment by sahat** [comment]
@deadcoder0904 I appreciate the effort, but I think it's best to leave it as is for the reasons outlined above. Having a guaranteed access to jQuery and Bootstrap libraries during development has a higher priority than a minor CDN optimization in this particular case.
