### ISSUE TITLE
Anyone have an example of doing google 2 factor auth with this framework?

### ISSUE THREAD

**Issue by rstudner** [sahat/hackathon-starter#603]
I'm new to the ecosystem, so my apologies if the answer would be obvious.

This starter uses passport, and i've seen speakeasy.  I also know there is a passport-totp library.

Oddly, I don't seem to ever see any examples that integrate(?) passport WITH speakeasy.

Any thoughts/help -- greatly appreciated.

**Comment by YasharF** [comment]
Are you having an issue with Hackathon Starter, or are you trying to do integration of Google 2-factor Auth in a different project aka WITH speakeasy?  If the issue is the latter, for example you are looking for an example of passport WITH speakeasy, passportJS or Speakeasy projects are probably the more relevant places to ask for them:  https://github.com/speakeasyjs/speakeasy/issues ,  https://github.com/jaredhanson/passport/issues
