### ISSUE TITLE
jQuery not supported; Typescript; Bower

### ISSUE THREAD

**Issue by gempain** [sahat/hackathon-starter#641]
Hello,

I don't have enough words in my vocabulary to tell you how grateful I am for this project. To me the most recurrent problem you solve is that one shouldn't build auth again, again and again, and also you provide a good base for a production app.

First, the only issue I have noticed is that jQuery 3 is not supported by the Bootstrap 3 version included in the project. Updating to version 3.3.7 should [fix the problem](https://github.com/twbs/bootstrap/issues/16834).

Beyond that, I think this project is an excellent basis, and could be improved by migrating to Typescript and adding support for Bower (which would fix the above issue in the long run).

Once migrated to TS, a slight refactor of the structure to separate MongoDB connection setup, controllers etc, would probably improve the usability.

Finally, I think that setting up nodemon by default, and including handy preinstall scripts such as `bower install` in the `package.json` could improve the workflow.

I will be working on some of these aspects but don't promise I can make a pull request as I am not sure that some of my design decisions are those you'd make yourself. Would love to discuss it with you. I think this project can become an even stronger base start.

Please know that I am aware that including these technologies would most likely lead this project to a mini-framework, which it somehow is already, but I think you've got an amazing concept here !

Keep up the great work !

All the best;

**Comment by YasharF** [comment]
Regarding the jQuery 3 issue, I suspect Bootstrap 4 upgrade is going to resolve it: https://github.com/sahat/hackathon-starter/issues/766

Bower seems to be getting deprecated and right now just being maintained. A note on their website states "While Bower is maintained, we recommend yarn and webpack for new front-end projects!".

TypeScript does have some benefits, but considering that it is a superset of JavaScript, it may be adding too much complexity for new developers, especially in the context of a weekend hackathon.  My 2 cents would be to try to keep things simple instead of having to have people learn TypeScript so they could do their project during a hackathon event.

**Comment by niallobrien** [comment]
I agree with @YasharF
