### ISSUE TITLE
Should MongoStore (session store) be removed?

### ISSUE THREAD

**Issue by sahat** [sahat/hackathon-starter#669]
Trying to get some feedback from people who use this project. Do you think MongoStore should be removed?

This package allows you maintain the session between the server restarts. 

```js
const MongoStore = require('connect-mongo')(session);

app.use(session({
  resave: true,
  saveUninitialized: true,
  secret: process.env.SESSION_SECRET,
  store: new MongoStore({
    url: process.env.MONGODB_URI || process.env.MONGOLAB_URI,
    autoReconnect: true
  })
}));
```
I am considering removing it in favor of going back to the default in-memory store which doesn't require any additional packages. This also gives you more flexibility to insert your favorite database store like Redis or RethinkDB. If there is enough interest to keep MongoStore, I will leave it alone.

**Comment by slidenerd** [comment]
I read connect-mongo just now. It seems like the sessions are stored in the database for 14 days by default. It also had a section where it talks about reusing an existing database connection. Since you already have the user model and user controller that opens another connection, I think connection reuse would be great if you implement it. I dont see any reason why this should be removed however

**Comment by pdhoward** [comment]
keep +1
