### ISSUE TITLE
Mobile app authentification ?

### ISSUE THREAD

**Issue by tugal** [sahat/hackathon-starter#699]
Hi all,

I wonder if API for social login (oauth 1 & 2) is suitable for mobile app login ?
I mean, mobile app login user from social provider, then the received token is sent to the api to be checked and log the user 

Thanks,

**Comment by jpca999** [comment]
nobody replies back here. I wonder Is there a better open source starter project out there better than hackathon-starter ?

**Comment by YasharF** [comment]
Hackathon starter has the proper wiring.  The social login provider and the mobile browser on the user's device need to be able to properly handle it.  To make sure it works:
- You would need to test the social login provider.
- You will need to test the login on mobile devices that your users are going to use.

**Comment by danielcrk** [comment]
@YasharF Seems like a lot of people (including me) use this as a starter for non-hackathon projects (i found it by searching for "expressjs boilerplate"), would it perhaps a good idea to fork this into a new project and make it more generic? What do you think?

**Comment by niallobrien** [comment]
More generic in what sense? I maintain a fork of this project in which I've improved certain aspects but you'll never have a one-size fits all kinda solution.

**Comment by niallobrien** [comment]
Generally speaking, this project is more aimed at giving a solid foundation for a responsive web app. Should you need to integrate it with a native mobile app, then you might be best to fork this project and strip out all of the bits you don't need and make any such changes. Otherwise, there's nothing stopping this project working within a mobile web browser (a mobile app can still utilise a browser window). Closing for now.
