### ISSUE TITLE
Cannot GET /api/bitgo

### ISSUE THREAD

**Issue by shahzeb1** [sahat/hackathon-starter#725]
URL: https://hackathonstarter-sahat.rhcloud.com/api/bitgo

Screenshot: 
![image](https://user-images.githubusercontent.com/1383831/29492858-a2900930-853e-11e7-906f-6c389b76962a.png)

**Comment by JonLim** [comment]
Looks like BitGo was removed because of a dependency issue, which was committed in https://github.com/sahat/hackathon-starter/commit/fc464d8728b862e567a4df51c3a4e0747be353bf, and brought up in issue #537.

Might be a good idea to clean it up and remove references to it from the `API Examples` page?

I can take that on, if it's cool?

**Comment by YasharF** [comment]
PR merged.  Thank you.
