### ISSUE TITLE
DeprecationWarning: ensureIndex() is deprecated in Mongoose >= 4.12.0, use createIndex() instead

### ISSUE THREAD

**Issue by aquartier** [sahat/hackathon-starter#739]
This warning message only appears when I start my new project.
It's probably **connect-mongo** is calling ensureIndex() somewhere.

**Comment by aquartier** [comment]
This should be fixed by just upgrading **connect-mongo** to 2.0.0

https://github.com/Automattic/mongoose/issues/5692
https://github.com/jdesboeufs/connect-mongo/blob/master/CHANGELOG.md#200--2017-10-09

**Comment by YasharF** [comment]
I just tried a clean hackathon-starter project to re-replicate the warning, and it doesn't seem to be an issue any more.  If I understood it correctly, the underlying issue seemed to have been with connect-mongo was calling ensureIndex() under the hood  https://github.com/Automattic/mongoose/issues/5692#issuecomment-335023397 . That npm module got fixed with https://github.com/jdesboeufs/connect-mongo/pull/269  which got folded into  connect-mongo v2.0.0 release.

Hackathon-starter its version of connect-mongo about two weeks ago [here](https://github.com/sahat/hackathon-starter/commit/11bb9a74ddaf1413a651d5856a9f55965917c6db), and this problem is now resolved.
