### ISSUE TITLE
Is It possible to drop all the frontend on hackathon-starter and use create-react-app instead?

### ISSUE THREAD

**Issue by mvww11** [sahat/hackathon-starter#795]
Is It possible to drop all the frontend on hackathon-starter and use create-react-app instead?
Would you give me some guideline in order to do that? 
Sorry, im on my second fullstack project.

**Comment by niallobrien** [comment]
Hi @mvww11 - yes it is possible but to be honest, you're probably best building a REST API server with Express from scratch and referring to this project to see how you can setup the routes, controllers, models etc.
You see, in your case you just want Express to return JSON, not rendered views. This will mean getting rid of all views (except the main one where you'll load your React app), removing all references to clientside JS and CSS, and certain middleware that's specific for a traditional server side rendered application. There are many tutorials out there for creating REST APIs with Express (probably more than how you'd create a traditional web app like Hackathon Starter does, which is why I think this project is so valuable).
But as I said, for your use case, this project (as it is) probably isn't a great fit. I suggest you fork it and remove all of the parts you don't need or simply build from scratch.
Thanks.
