### ISSUE TITLE
Add Helmet

### ISSUE THREAD

**Issue by marcospgp** [sahat/hackathon-starter#817]
[Helmet npm package](https://www.npmjs.com/package/helmet) recommended in [Express security best practices](https://expressjs.com/en/advanced/best-practice-security.html).

**Comment by nacimgoura** [comment]
[lusca](https://github.com/krakenjs/lusca) is already used and does the same thing.

**Comment by YasharF** [comment]
At the moment HelmetJS has about 10 times more users (npm download stats) than Lusca.  
Blocking questions:  Going through Hackathon Starter's code base, are there functionalities that will be lost if we drop Lusca in favor of Helmet?    What new benefits will we get that is currently not in the project?

**Comment by marcospgp** [comment]
HelmetJS doesn't seem to provide anti-CSRF functionality, but it seems to provide other things that lusca doesn't.

**Comment by YasharF** [comment]
Helmet currently provides the following 

- contentSecurityPolicy for setting Content Security Policy

  - On the plus side, it helps prevent XSS by restricting external resources (aka CDNs, etc for assets and scripts).  We are sanitizing the inputs with Express Validator (Rule 6 athttps://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet ).  On the the other side there is a high chance that during a course of a hackathon the developers would want to quickly add external assets or content to get their prototype going, and content security policy is definitely going to come in their way.

- expectCt for handling Certificate Transparency
  - CT applies if SSL is enabled.  Out of the box that is not the case for this project.
- dnsPrefetchControl controls browser DNS prefetching
  - The issue with DNS prefetching is that it may appear that a user is browsing external links on the site when they are not and if their privacy has already been compromised then the links could be attributed as part of their browsing activity (aka a government in a country has a ban on certain 3rd party website and is monitoring some individual's internet connection; one of the banned sites is listed by a link on a page in a hackathon-starter based project like a forum that someone built using hackathon-starter.  Then that government can accuse the individual for visiting a banned site that they didn't actually visit)
- frameguard to prevent clickjacking
  - Frameguard would block the site from being rendered in an iframe on other sites in order to avoid users being tricked into clickjacking.
- hidePoweredBy to remove the X-Powered-By header
  - Removes the X-Powered-By header so attackers would not be able to figure out what type of server they are accessing).  This can also be done by adding `app.disable('x-powered-by');` in app.js
- hpkp for HTTP Public Key Pinning
  - Applies applies if SSL is enabled.  Out of the box that is not the case for this project.
- hsts for HTTP Strict Transport Security
  - Applies applies if SSL is enabled.  Out of the box that is not the case for this project.
- ieNoOpen sets X-Download-Options for IE8+
  - Applies if the users on old versions of IE such as IE8.  IE8, IE9, and IE10 went in EOL on Jan 12, 2016.  If a user is using any of these browsers, they probably already have a whole lot of other vulnerabilities and are being actively bugged by MS (KB3123303).
- noCache to disable client-side caching
  - This is not really a bug.  It just prevents users from caching old versions of files such as javascripts, etc.  It would be helpful if you have a client side vulnerability (aka a client side javascript with a bug) that you have patched.
- noSniff to keep clients from sniffing the MIME type
  -  This would be an attack vector if content from untrusted 3rd parties or malicious users are being displayed back on the site.  For example, a user would upload a .jpg file, where its content is actually a a crafted HTML/Javascript.  I think in case of hackathon-starter, if the developers are planning to display untrusted data, they should consider dealing with the attack vectors for their upload, etc. process.
- referrerPolicy to hide the Referer header
  - Allows users that are leaving for other websites by clicking on links in a hackathon-starter project to hide that they came from the site.
- xssFilter adds some small XSS protections
  - Sanitizing inputs and quary parameters would also do this.

**Comment by YasharF** [comment]
By default only the following are enabled:

dnsPrefetchControl
frameguard
hidePoweredBy
hsts
ieNoOpen
noSniff 
xssFilter

We can manually set the flags in express configs or as middlewares.  It would probably make more sense to just add helmet though since it is actively maintained.

**Comment by YasharF** [comment]
Frameguard and xss were the main drivers for using helmet.  It looks like that those two features are provided by Lusca and already in use in hackathon-starter: https://github.com/sahat/hackathon-starter/blob/master/app.js#L95

**Comment by YasharF** [comment]
Looking at https://github.com/krakenjs/lusca it looks like the feature set is redundant., since it currently  has the following methods:

> lusca.csrf()
> lusca.csp()
> lusca.xframe()
> lusca.p3p()
> lusca.hsts()
> lusca.xssProtection()
> lusca.nosniff()
> lusca.referrerPolicy()

It doesn't look like if there is a method to replace hidePoweredBy though.

**Comment by YasharF** [comment]
hidePowerBy equivalent is now implemented in hackathon starter with https://github.com/sahat/hackathon-starter/commit/69e66def883046a095bd0edce54de091edd7bd37
