### ISSUE TITLE
Paypal Integration: Break on success & failure 

### ISSUE THREAD

**Issue by GeekRishabh** [sahat/hackathon-starter#855]
The Heroku link breaks and is redirected to `http://localhost:8080/api/paypal/success?paymentId=PAY-1ND280637A326803CLLZ6EOA&token=EC-2NR76106M86837311&PayerID=9PP8UJ4DYAYHA`

**Comment by YasharF** [comment]
By Heroku, do you mean the demo site that is listed on this repo?

**Comment by GeekRishabh** [comment]
Yes

**Comment by YasharF** [comment]
Unfortunately the demo site currently is more less just to give you a feel of the project, and doesn't have valid credential or modified call back registration. In other words currently the demo deployment is literally a deployment of the git repo, which means it is using the API credentials and callback configs that are in the .env.example.  As far as the credentials go, most of the credentials in the .env.example are invalid since publishing valid keys publicly have a high chance of them being abused.

You can use your own copy of the project with your own _valid_ API keys from Paypal or the other API providers and based on your development system or deployemnt location adjust the Paypal call back URLs through environment variables listed at https://github.com/sahat/hackathon-starter/blob/master/.env.example#L53 .

At some point, we may adjust the demo deployment with custom env variables, but right now it is going to be the defaults in the .env.example.
