### ISSUE TITLE
Docker, assets are missing

### ISSUE THREAD

**Issue by daveybrown** [sahat/hackathon-starter#869]
When following the Docker instructions, the result is 404 missing files for jquery, bootstrap and popper.

I think it's related to postinstall in package.js but I'm not sure how to fix it.

![image](https://user-images.githubusercontent.com/15802017/41775269-33ed057c-761b-11e8-88f9-20b0b6f1b340.png)

**Comment by YasharF** [comment]
I suspect it is because I forgot to replicate the asset copies during the Bootstrap 4 upgrade changes.

You would need to replicate the copies in https://github.com/sahat/hackathon-starter/blob/master/package.json#L12 in to the Dockerfile like https://github.com/sahat/hackathon-starter/blob/master/Dockerfile#L6

If that fixes it, would you be able to submit a PR?

**Comment by daveybrown** [comment]
Hi, thanks for the pointer in the right direction. Sure thing, if it fixes it I'll submit a PR. Thanks!

**Comment by AhsanAyaz** [comment]
@YasharF the copies couldn't be replicated because of the `.dockerfile` excludes `node_modules`.
Therefore, couldn't copy from something that's excluded before the build process begins.
I fixed it. Will create a PR.
