### ISSUE TITLE
Bold weight applied by default on Mac OS

### ISSUE THREAD

**Issue by peterblazejewicz** [sahat/hackathon-starter#900]
@sahat 
The default font declaration makes the body text looks overweighted I think. 
Was that intentional?

https://github.com/sahat/hackathon-starter/blob/master/public/css/themes/default/_variables.scss#L12

![image](https://user-images.githubusercontent.com/14539/44491915-f90a2e80-a662-11e8-8b6e-8717d6dc5b24.png)

For comparison, default system font:

![image](https://user-images.githubusercontent.com/14539/44491953-1939ed80-a663-11e8-884e-a5895bc9204e.png)

**Comment by YasharF** [comment]
When doing bootstrap 4 upgrade, the default fonts turned out to be too light compared to the pre-bootstrap 4 version on Windows 10 with Chrome which I was doing:
**_Pre bootstrap 4 upgrade:_**
![image](https://user-images.githubusercontent.com/6448697/44496227-72386000-a628-11e8-95e4-940da97af433.png)

**_Post-upgrade without the extra line for the heavy font:_**

![image](https://user-images.githubusercontent.com/6448697/44495531-20420b00-a625-11e8-94ac-231fa9922916.png)

Adding https://github.com/sahat/hackathon-starter/commit/56f48691dfcfd709e1ed352218f7d6d0ba52bc89 made it better by turning it to:

![image](https://user-images.githubusercontent.com/6448697/44495507-06082d00-a625-11e8-9bce-409634754c66.png)

It looks like that was not the best way to fix it as it is causing rendering issues on Macs.  I'm open to other ways to fix the light font issue that showed up so it doesn't cause issues on Macs.

**Comment by estevanmaito** [comment]
@YasharF could you try reproducing this again? I tested both Chrome and Firefox on Windows 10 and Ubuntu 18, with `HelveticaNeue-CondensedBold` and without it, and every case rendered `Arial`.

**Windows 10**
_Chrome_
`"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"`

_Firefox_
`"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0"`

**Ubuntu**
_Chrome_
`"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"`

_Firefox_
`"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"`

**Comment by YasharF** [comment]
I was not able to reproduce it since I don't have a mac :(

Prior to the Bootstrap 4 upgrade `$headings-font-family: "HelveticaNeue-CondensedBold", "Helvetica Neue", Arial, sans-serif;` didn't exist and I added it https://github.com/sahat/hackathon-starter/blob/master/public/css/themes/default/_variables.scss#L12 since on Windows/Chrome when the page rendered the font looked lighter than when it was using Bootstrap 3.  https://github.com/sahat/hackathon-starter/issues/900#issuecomment-415220789 shows the screenshots.  Maybe a fix would be to remove the line that I added, and instead, come up with a different way of making the font look like the old rendering and not lighter.

**Comment by estevanmaito** [comment]
Does removing this `$font-family-base: "HelveticaNeue-CondensedBold", "Helvetica Neue", Arial, sans-serif;` still renders thin fonts for you on Windows 10? (I tested removing directly in the browser - `font-family`, just removing the condensed bold font, and nothing changed).

It looks like it was a problem with webkit fonts, and seems to be corrected (at least in my tests locally): https://stackoverflow.com/questions/41995957/font-weight-in-bootstrap-3-and-bootstrap-4-are-different

**Comment by stevegk** [comment]
Macs have HeleveticaNeue-CondensedBold installed so Safari and presumably other browsers pick up this font and use it, although interestingly, Firefox uses plain Helvetica Neue. On windows Helvetica fonts are not usually installed and the browsers fallback to using Arial. Removing the HelveticaNeue-CondensedBold will fix this for macs and keep the Bootstrap 3 fonts.

**Comment by neighlyd** [comment]
[Implemented fix in PR #975](https://github.com/sahat/hackathon-starter/pull/957)

**Comment by YasharF** [comment]
Thank you @neighlyd
