### ISSUE TITLE
Base URL is HTTPS but redirect callback is HTTP

### ISSUE THREAD

**Issue by fjsuarez** [sahat/hackathon-starter#923]
I deployed the app on Microsoft Azure, and it is being served over HTTPS. However, when I try to use the Facebook login, the redirect URL is HTTP, which is no longer permitted by Facebook.
I understand this is done using Passport in the following lines:
```
passport.use(new FacebookStrategy({
  clientID: process.env.FACEBOOK_ID,
  clientSecret: process.env.FACEBOOK_SECRET,
  callbackURL: '/auth/facebook/callback',
  profileFields: ['name', 'email', 'link', 'locale', 'timezone', 'gender'],
  passReqToCallback: true
},
...
```
The path in callbackURL is being added to the base URL, but I don't understand why it uses HTTP when the website is being served over HTTPS.

**Comment by YasharF** [comment]
Do you have "Enforce HTTPS" turned on in Facebook's app settings for your app?

**Comment by fjsuarez** [comment]
As of October 2018, it is mandatory. The toggle switch is disabled.

**Comment by nicholasgonzalezsc** [comment]
@fjsuarez What is the `redirect_uri` in the request to authenticate with facebook? 
When the `callbackUrl` is set to a relative path, `passport-oauth2` will try to create an absolute url for you using the initial request. So if the initial request is `http` or `trust proxy` is not enabled, then it will use `http` instead of `https`. 

Here are the relevant lines:
https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L141
https://github.com/jaredhanson/passport-oauth2/blob/master/lib/utils.js#L29

Some helpful packages that could potentially be added to the starter for "prod" environments:
- `helmet` https://helmetjs.github.io/docs/
- `express-enforces-ssl` https://github.com/hengkiardo/express-enforces-ssl

**Comment by fjsuarez** [comment]
> What is the `redirect_uri` in the request to authenticate with facebook?
> When the `callbackUrl` is set to a relative path, `passport-oauth2` will try to create an absolute url for you using the initial request. So if the initial request is `http` or `trust proxy` is not enabled, then it will use `http` instead of `https`.

It is as stated in OP. As far as I understand, I'm making the initial request as https.

**Comment by amit-bhadra** [comment]
I am also facing the same issue. I am using **ngrok https link** to test facebook auth.
This is the error facebook redirect page is showing: "Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://"

**Comment by fjsuarez** [comment]
Yes, that is the error. In my case, however, I had no issues testing locally (localhost:8080), even without using ngrok.

**Comment by YasharF** [comment]
Perhaps the better solution would be to change all of the callbackURLs to use the BaseURL variable, In that way, the developers can just put the URL in the env variable and it would replicate everywhere that is applicable.  https://github.com/sahat/hackathon-starter/blob/master/.env.example#L1 . I suspect having that extra config needs to have some conditions associated with it to prevent new developers to get confused.  Perhaps, there needs to be some type of run-time referer URL check, override, or something.

**Comment by YasharF** [comment]
I am able to replicate this issue; looking into it.

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/c1896bb6d4adde062b1f14c9a3d53dddc4a02356

**Comment by offirpeer** [comment]
I have the same issue:
https://stackoverflow.com/questions/58190107/facebook-login-error-base-url-is-https-but-redirect-callback-is-http
