### ISSUE TITLE
bcrypt-nodejs package hasn't been updated in six years

### ISSUE THREAD

**Issue by rmfranciacastillo** [sahat/hackathon-starter#948]
Hi,

Since [bcrypt-node](https://www.npmjs.com/package/bcrypt-nodejs) hasn't been updated in 6 years, wouldn't it be better to update to [bcrypt](https://www.npmjs.com/package/bcrypt) package

I know this is not for production but It'll be nice to have a package that is constantly updating.

Cheers

**Comment by YasharF** [comment]
I had no idea.  Yes we need to migrate off of bcrypt-nodejs since per https://github.com/shaneGirish/bcrypt-nodejs
```
Note: This project is not actively maintained
If you are looking for a javscript-only bcrypt implementation we recommend you use bcrypt.js, which is based on bcrypt-nodejs."
```

It looks like there are potentially two different options though.  The maintainers seem to be activly engaged in both projects. We need to figure out the trade-offs for using either one:

- https://www.npmjs.com/package/bcryptjs
- https://www.npmjs.com/package/bcrypt

**Comment by rmfranciacastillo** [comment]
Hmm. Seems like bcrypt is more active since it's repo has been updated just 6 days ago. 

If you want, I can do pull request with an update to it.

**Comment by YasharF** [comment]
Not necessarily about this case, but in general, the frequency of code updates doesn't necessarily mean it is a better choice, because the existing code may simply be more mature and bug-free requiring fewer updates.  The underlying BSD algorithm is very stable with only four updates since 1999, including the last update in 2014: https://en.wikipedia.org/wiki/Bcrypt#Versioning_history

**Comment by YasharF** [comment]
https://stackoverflow.com/questions/22801593/security-differences-with-bcrypt-node-js-modules

**Comment by YasharF** [comment]
Since the c++ bcrypt will be 30% faster than the plain js implementation, let's opt for that version.  It does rely on node-gyp which can create some confusion in the initial `npm install` of the project, however, node-gyp is already in the dependency graph as part of the dependencies for node-sass.

**Comment by sahat** [comment]
👍

**Comment by YasharF** [comment]
Fixed with https://github.com/sahat/hackathon-starter/commit/454da6261ea8fb14427f183f9c01ab8c6a3c972d
