### ISSUE TITLE
Migrate the Instagram API Integration

### ISSUE THREAD

**Issue by YasharF** [sahat/hackathon-starter#964]
Facebook is in the process of shutting down the instagram api endpoint due to privacy issues.  Some functions, more specifically for business accounts may be available under the graph api for instagram.
The docs for the new API platform is located at https://developers.facebook.com/products/instagram

Already deprecated form the instagram apis:

- Follower List - to read the list of followers and followed-by users
- Relationships - to follow and unfollow accounts on a user’s behalf
- Commenting on Public Content - to post and delete comments on a user’s behalf on public media
- Commenting - to post and delete comments on a user’s behalf on owned media
- Public Content - to read any public profile info and media on a user’s behalf
- Likes - to like and unlike media on a user’s behalf
- Subscriptions - to receive notifications when media is posted

Planned for shutdown in early 2020:
- Basic - to read a user’s profile info and media

**Comment by YasharF** [comment]
https://github.com/sahat/hackathon-starter/commit/8e60de3777e2988e77518eeb619f86ad8e7bfcea removed the currently deprecated parts of the Instagram API and fixed scope permission issue.

**Comment by YasharF** [comment]
The new API: https://developers.facebook.com/docs/instagram-basic-display-api/

**Comment by adilanchian** [comment]
Going to take a stab at this and hopefully have something for ya shortly :)

**Comment by adilanchian** [comment]
Looked through the code here, not sure if I will have time to complete this so I will leave some thoughts here:
- `instagram-node` is 5 years outdated (https://www.npmjs.com/package/instagram-node) this needs to be removed
- There is a new flow for sign in for Instagram that is not included in `passport` which means a new authentication setup will be needed (https://developers.facebook.com/docs/instagram-basic-display-api/getting-started)
- I wasn't able to find any node packages that support the new Instagram APIs, so this will have to be re-written as well

It sort of stinks because this project is heavily setup with Passport and 3rd party libraries, but doesn't really seem like Instagram will play nice with the rest of this.

More than happy to discuss if needed, but I do think this will a much larger change than expected :)

**Comment by YasharF** [comment]
If I recall correctly, "sign in with Instagram" is no longer available.  Their API is no longer an authentication solution.  The part that is supposed to be there is the Instagram Basic Display which you found.  With that said, I suspect we can move forward without any Instagram specific libraries:
- For oAuth, we might be able to just use the OAuth2Strategy, like how we have been setting up Foursquare or Quickbooks APIs: https://github.com/sahat/hackathon-starter/blob/master/config/passport.js#L569 and https://github.com/sahat/hackathon-starter/blob/master/config/passport.js#L671) .
- For the specific data API calls, we can potentially do the same thing as we did with fbgraph: move off of the unmaintained package and just started to call the API endpoints using axios (https://github.com/sahat/hackathon-starter/pull/1094/files)

**Comment by adilanchian** [comment]
Hey @YasharF - Ya this makes a lot of sense. So to sum up the tasks here:

1. Setup OAuth2Strategy for Instagram (similar to Foursquare & Quickbooks)
2. Change basic endpoints to use axios
3. Remove all the crust of the old instagram API integration

**Comment by zantetsuken88** [comment]
I'm interested in working on this, would that be ok?

**Comment by T-Stewart** [comment]
https://github.com/sahat/hackathon-starter/pull/1120#issue-517306512
  
Hi! I've opened a PR which I think is 99% of the way to addressing the issue but I'm running into issues during testing and would appreciate a 2nd pair of eyes (details in the PR)
