### ISSUE TITLE
After 1 hour Google tokens getting expired.

### ISSUE THREAD

**Issue by tanaydin** [sahat/hackathon-starter#977]
Hello,

Unfortunately, Google tokens are expiring. So it needs a solution for this.

**Comment by YasharF** [comment]
I suspect that this is a more wide-spread issue that just in the Google API example since we are not using the expiration values returned by the oAuth calls for any of the APIs. When adding support for QuickBooks earlier today, I added the expirations with the refresh token from Intuit https://github.com/sahat/hackathon-starter/commit/285b6b170d029322b0b000f056c2ce9331728398#diff-c6601fa9f2ae68b5ce23cfd416544f27R598

Potential solution might be to add the expirations to the other tokens and instead of just checking to see if we have a token in the isAuthorized method at https://github.com/sahat/hackathon-starter/blob/master/config/passport.js#L628, the logic in isAuthorized can also check to see if the token has not been expired with something like `accessTokenExpires.isAfter(moment())`, and if it has expired refresh or request a new token.

**Comment by YasharF** [comment]
Confirming that the Quickbooks example has the same problem; temporary user workaround is to go to the account page Unlink the provider, and retry so a new token is obtained.

**Comment by YasharF** [comment]
Fixed by https://github.com/sahat/hackathon-starter/commit/dcfad818db297ce4d56412ac491558d185ef1601
