### ISSUE TITLE
POST Signup method in User controller crashes app

### ISSUE THREAD

**Issue by edgarrt** [sahat/hackathon-starter#985]
Using a windows machine with the prereqs met. 
I completed all steps in getting started and can get the app running
I haven't modified any files, but when I try to create a new user via the signup page the connection resets and terminal is no longer running app.js.
No other warnings.  

I have tried using both a local MongoDB instance and Mongo Atlas cluster
I updated the .env.example MONGODB_URI in the Mongo Atlas Scenario

I have pinpointed the error to line 106 in user.js inside the controllers directory.
The user.save method does not execute. 

On the login in page, if I put dummy email and password, I can see the POST /login attempt and error flashes on /login but on signup page after pressing submit, node app.js kicks out.

**Comment by edgarrt** [comment]
I tried bypassing the user variable creation entirely with the following, but still crashes

>     User.create({
>       email: req.body.email,
>       password: req.body.password
>     }, function (err, small) {
>       if (err) {
>         return handleError(err);
>       }
>       // saved!
>       res.redirect('/signup');
>     });
>

**Comment by YasharF** [comment]
Can you try the following commands in the terminal in the project folder and provide the outputs here?

```
node -v
npm -v
npm test
```

**Comment by edgarrt** [comment]
node -v
v8.9.3

npm -v
5.5.1

npm test

> hackathon-starter@5.1.4 test j
> nyc mocha --timeout=10000 --exit



✓ App is running at http://localhost:8080 in development mode
  Press CTRL-C to stop

  GET /
GET / 200 622.235 ms - -
    √ should return 200 OK (1291ms)

  GET /login
GET /login 200 109.013 ms - -
    √ should return 200 OK (184ms)

  GET /signup
GET /signup 200 84.635 ms - -
    √ should return 200 OK (159ms)

  GET /api
GET /api 200 96.418 ms - -
    √ should return 200 OK (170ms)

  GET /contact
GET /contact 200 56.774 ms - -
    √ should return 200 OK (132ms)

  GET /api/lastfm
GET /api/lastfm 200 451.667 ms - -
    √ should return 200 OK (525ms)

  GET /api/twilio
GET /api/twilio 200 47.588 ms - -
    √ should return 200 OK (120ms)

  GET /api/stripe
GET /api/stripe 200 59.003 ms - -
    √ should return 200 OK (136ms)

  GET /api/scraping
GET /api/scraping 200 213.102 ms - -
    √ should return 200 OK (304ms)

  GET /api/lob
GET /api/lob 200 706.869 ms - -
    √ should return 200 OK (780ms)

  GET /api/clockwork
GET /api/clockwork 200 32.993 ms - -
    √ should return 200 OK (109ms)

  GET /api/upload
GET /api/upload 200 39.873 ms - -
    √ should return 200 OK (113ms)

  GET /random-url
GET /reset 404 2.801 ms - 144
    √ should return 404 (77ms)

  User Model
    √ should create a new user
    √ should return error if user is not created
    √ should not create a user with the unique email
    √ should find user by email
    √ should remove user by email
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
npm ERR! Test failed.  See above for more details.

**Comment by YasharF** [comment]
Your NodeJS version seems to be an old out of date version, and there may have been some errors during `npm install` potentially due to npm bugs that may have been resolved in the later versions of npm.

Try the following steps in order
1. Uninstall NodeJS
2. Verify that NodeJS is uninstalled: `node -v` and `npm -v` should give some kind of error instead of a number.
3. If you are on Windows 10, I would recommend switching to Windows 10 Bash (Ubuntu from Windows Store).  The compilers are more streamlined than Visual Studio/Windows-based tools.
4. Download and install the current version of NodeJS: https://nodejs.org for Windows, or for Windows 10 Bash/Ubuntu try:
```
sudo apt-get update && sudo apt-get upgrade -y
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential
```

If you are using Windows 10 bash, I would recommend creating a folder such as c:\temp from windows, and then going into it from Bash using `cd /mnt/c/temp` and starting your project clone, etc in there.  Your MongoDB instance does not need to be running through bash and can be running from Windows or in the cloud.

**Comment by edgarrt** [comment]
I used the Windows 10 Bash route and it works perfect now. Thanks!
